version: "3"

services:
    flask_app:
        build: .
        restart: always
        ports:
            - "80:5000"
        # environment:
        #     POSTGRES_DB: ${POSTGRES_DB}
        #     POSTGRES_PASSWORD: ${POSTGRES_PASS}
        # links:
        #     - postgres
            
        depends_on:
            # - postgres
            - db
            - redis
            
        container_name: flask_app


    db:
        image: mysql:latest
        restart: always
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: 'mysql_db'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: '1234'
            MYSQL_ROOT_PASSWORD: '1234'
        
        container_name: flask_mysql

    # postgres:
    #     image: postgres:11-alpine
    #     restart: always
    #     environment:
    #         POSTGRES_DB: ${POSTGRES_DB}
    #         POSTGRES_PASSWORD: ${POSTGRES_PASS}
    #     volumes:
    #         - .postgres-data:/var/lib/postgresql/data
    #     container_name: flask_postgres

    redis:
        image: redis
        volumes:
             - ./data:/data
        ports:
             - 6379:6379