version: "3"

services:
    flask_app:
        build: .
        restart: always
        ports:
            - "5000:5000"
        
        links:
            - db
            
        depends_on:   
            - db
            - redis
            
        container_name: flask_app


    db:
        image: mysql:latest
        restart: always
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: 'mysql_db'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: '1234'
            MYSQL_ROOT_PASSWORD: '1234'
        
        container_name: flask_mysql

    

    # redis:
    #     image: redis:alpine
    #     restart: always
    #     volumes:
    #          - ./data:/data
    #     ports:
    #          - 6379:6379
             
    #     container_name: flask_redis